### ISSUE TITLE
npm run dev not working

### ISSUE THREAD

**Issue by titan901** [KrauseFx/FxLifeSheet#70]
```
C:\Users\TR>npm run dev

>@ dev C:\Users\TR
>source .keys && npm run prettier && npm run typescript && heroku local

'source' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `source .keys && npm run prettier && npm run typescript && heroku local`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\TR\AppData\Roaming\npm-cache\_logs\2020-06-09T19_55_07_785Z-debug.log
```

> Also can we get a more detailed instructions on how to install. I'm not a programmer and I'm struggling quite a bit to get this installed. I'd appreciate it very much. <3

**Comment by JakeCasey** [comment]
This project will take a fair amount of programming knowledge to set up unfortunately. It looks like you're on windows, which will complicate installation even further. The error you're seeing is because the command ```source``` probably doesn't exist on Windows. I think Windows has a bash shell that you can use these days but I don't know for sure? I recommend moving forward on a unix-like operating system like mac or linux.  But essentially you'll need to get all of the credentials explained in the main readme. And create a .keys file in the main dir. (or inject env variables into the node.js process in whatever way you like)

```
export TELEGRAM_BOT_TOKEN=""
export TELEGRAM_USER_ID=""
export TELEGRAM_CHAT_ID=""

export DATABASE_URL=""

export LIFESHEET_JSON_URL=""

export OPEN_CAGE_API_KEY=""
export WEATHER_API_KEY=""
```
The Telegram Bot Token, user id, and chat id, can be retrieved by creating a bot using these instructions: https://core.telegram.org/bots

Database URL is retrieved by either creating a local postgres database or using a managed database service. (You may have to modify the postgres.ts further to include things like username/password, ssl cert, or you can use the connectionstring provided by your service)

Lifesheet you can leave blank to use the default lifesheet. I believe this option is included if you wanted to remotely host the lifesheet itself.

You can sign up for an OPEN_CAGE_API key here https://opencagedata.com/api

All-in-all this is far from a plug-and-play QS setup, and is much more targeted at developer users and that's totally cool because it seems pretty great! But if you're determined to get this set up for yourself I'd be prepared to do a fair bit of learning, or hiring somebody to do it for you. Best of luck!

**Comment by skywinder** [comment]
@JakeCasey thanks for explanation. it would be nice even to put this steps into readme. 👍

**Comment by titan901** [comment]
@JakeCasey Thank you for the reply! I missed it and only just saw your comment. I'm prepared to get this set up. I'm currently on Arch Linux system. Now where do I start?

**Comment by JakeCasey** [comment]
@titan901 That's a long time ago bro. I don't even remember how to set it up haha. You'll have to install node, install the packages, and find all those keys I mentioned in the above post, you'll also probably want to deploy it somewhere, which is just beyond the scope of what I can help with. I'd recommend doing a lot of node.js tutorials and you'll understand how to deploy it eventually! Sorry I can't be of more help! :(

**Comment by KrauseFx** [comment]
Sorry everyone, I have GitHub notifications turned off, so I completely missed this thread. Thanks @JakeCasey for jumping in to help. As he had already mentioned, this is a project targeted for developers, so it will be very difficult to setup, and isn't a plug & play. 

For now, I'm about to launch https://whereisfelix.today.

I'll close this issue for now, thanks everyone
